"""Generate a least-privilege Mosquitto 2.x configuration for the demonstration.

Anonymous access is disabled. Each role (replay producer, inference worker, read-only
monitor) gets its own random password and topic ACL. A listener is bound to loopback
unless TLS files are supplied: plaintext MQTT never leaves the host. Secrets are written
with mode 0600 to a git-ignored directory and never printed.
"""

from __future__ import annotations

import os
import secrets
import shutil
import subprocess
from dataclasses import dataclass
from ipaddress import ip_address
from pathlib import Path

from driftguard.streaming.contract import MAX_PAYLOAD_BYTES, SCHEMA_VERSION

ROLES = ("replay", "worker", "monitor")
ACL = f"""# Generated by `driftguard stream broker-config`. Deny-by-default per user.
user replay
topic write {SCHEMA_VERSION}/features/#

user worker
topic read {SCHEMA_VERSION}/features/#
topic write {SCHEMA_VERSION}/alerts/#
topic write {SCHEMA_VERSION}/system/#

user monitor
topic read {SCHEMA_VERSION}/alerts/#
topic read {SCHEMA_VERSION}/system/#
"""


@dataclass(frozen=True)
class TlsFiles:
    cafile: Path
    certfile: Path
    keyfile: Path


def render_config(
    directory: Path, *, port: int, bind: str = "127.0.0.1", tls: TlsFiles | None = None
) -> str:
    if not ip_address(bind).is_loopback and tls is None:
        raise ValueError("refusing a non-loopback listener without TLS")
    lines = [
        "# Generated by `driftguard stream broker-config`; do not expose publicly.",
        "per_listener_settings false",
        "allow_anonymous false",
        f"password_file {directory / 'passwords'}",
        f"acl_file {directory / 'acl'}",
        f"max_packet_size {MAX_PAYLOAD_BYTES + 1024}",
        "max_inflight_messages 20",
        "max_queued_messages 1000",
        "persistence true",
        f"persistence_location {directory / 'data'}/",
        "log_type error",
        "log_type warning",
        "log_type notice",
        "connection_messages true",
        f"listener {port} {bind}",
    ]
    if tls is not None:
        lines += [
            f"cafile {tls.cafile}",
            f"certfile {tls.certfile}",
            f"keyfile {tls.keyfile}",
            "tls_version tlsv1.2",
        ]
    return "\n".join(lines) + "\n"


def find_mosquitto_tool(name: str) -> Path:
    found = shutil.which(name)
    for candidate in (
        found,
        f"/opt/homebrew/opt/mosquitto/bin/{name}",
        f"/opt/homebrew/opt/mosquitto/sbin/{name}",
        f"/usr/sbin/{name}",
    ):
        if candidate and Path(candidate).is_file():
            return Path(candidate)
    raise FileNotFoundError(f"{name} not found; install Mosquitto 2.x")


def write_broker_files(
    directory: Path, *, port: int = 1883, bind: str = "127.0.0.1", tls: TlsFiles | None = None
) -> Path:
    """Write config, ACL, hashed password file and a 0600 credentials env file."""
    directory = directory.resolve()
    (directory / "data").mkdir(parents=True, exist_ok=True)
    os.chmod(directory, 0o700)
    passwords = {role: secrets.token_urlsafe(24) for role in ROLES}
    passwd_tool = find_mosquitto_tool("mosquitto_passwd")
    password_file = directory / "passwords"
    password_file.unlink(missing_ok=True)
    password_file.touch(mode=0o600)
    for role, password in passwords.items():
        subprocess.run(  # noqa: S603 - fixed tool path, no shell
            [str(passwd_tool), "-b", str(password_file), role, password],
            check=True,
            capture_output=True,
        )
    os.chmod(password_file, 0o600)
    _write_private(directory / "acl", ACL)
    _write_private(
        directory / "mosquitto.conf", render_config(directory, port=port, bind=bind, tls=tls)
    )
    env = [f"DRIFTGUARD_MQTT_HOST={bind}", f"DRIFTGUARD_MQTT_PORT={port}"]
    for role, password in passwords.items():
        env += [
            f"DRIFTGUARD_MQTT_{role.upper()}_USERNAME={role}",
            f"DRIFTGUARD_MQTT_{role.upper()}_PASSWORD={password}",
        ]
    env.append(f"DRIFTGUARD_DEMO_API_TOKEN={secrets.token_urlsafe(32)}")
    if tls is not None:
        env.append(f"DRIFTGUARD_MQTT_TLS_CA={tls.cafile}")
    _write_private(directory / "credentials.env", "\n".join(env) + "\n")
    return directory / "mosquitto.conf"


def _write_private(path: Path, text: str) -> None:
    path.unlink(missing_ok=True)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write(text)
